apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: gcr.io/$PROJECT_ID/demo-payment-service:latest	
      containers:
      - name: payment
        image: ${IMAGES}
        ports:
        - containerPort: 8080

